//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecIotAgent.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SecIotAgent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap Spinner_3 {
            get {
                object obj = ResourceManager.GetObject("Spinner-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR {
            get {
                return ResourceManager.GetString("STR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_BTN_AUTHENTICATION {
            get {
                return ResourceManager.GetString("STR_BTN_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configure Application과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_BTN_CONFIGUREAPPLIATION {
            get {
                return ResourceManager.GetString("STR_BTN_CONFIGUREAPPLIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configure Device과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_BTN_CONFITUREDEVICE {
            get {
                return ResourceManager.GetString("STR_BTN_CONFITUREDEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   어플리케이션을 사용하기위한 
        ///&apos;사용자&apos;, &apos;장치&apos;, &apos;지문&apos; 정보의 
        ///등록작업을 진행합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_BTN_REGISTRATION_MSG {
            get {
                return ResourceManager.GetString("STR_BTN_REGISTRATION_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서비스 재시작과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_BTN_SERVERSTATUS {
            get {
                return ResourceManager.GetString("STR_BTN_SERVERSTATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웹브라우저 실행하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_BTN_VIDEOMETTING {
            get {
                return ResourceManager.GetString("STR_BTN_VIDEOMETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View Log과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_BTN_VIEWLOG {
            get {
                return ResourceManager.GetString("STR_BTN_VIEWLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USB가 연결되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_HELP_DETECT_PLUGIN_USB {
            get {
                return ResourceManager.GetString("STR_HELP_DETECT_PLUGIN_USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기 등록된 정보를 초기화 합니다. 
        ///초기화 작업 시 저장 정보가 삭제 됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_HELP_INIT_INFORMATION {
            get {
                return ResourceManager.GetString("STR_HELP_INIT_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웹과 통신을 위한 Listen 아이피 정보를 지정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_HELP_IPADDRESS {
            get {
                return ResourceManager.GetString("STR_HELP_IPADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USB를 연결하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_HELP_NEED_PLUGIN_USB {
            get {
                return ResourceManager.GetString("STR_HELP_NEED_PLUGIN_USB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   웹과 통신을 위한 PORT 정보를 지정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_HELP_PORT {
            get {
                return ResourceManager.GetString("STR_HELP_PORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   클라이언트에서 접속 가능합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_HELP_SERVERSTATUS_MSG {
            get {
                return ResourceManager.GetString("STR_HELP_SERVERSTATUS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인 메뉴 선택시 호출할 웹페이지의 정보를 지정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_HELP_WEBBROWSER {
            get {
                return ResourceManager.GetString("STR_HELP_WEBBROWSER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Insert IP Address...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_IPADDRESS_PLACEHOLDERTEXT {
            get {
                return ResourceManager.GetString("STR_IPADDRESS_PLACEHOLDERTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인증 및 설정 상태를 확인하고 필요한 작업을 수행하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_MSG_MAINHELP {
            get {
                return ResourceManager.GetString("STR_MSG_MAINHELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   로그인하기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_SA_BTN_LOGIN {
            get {
                return ResourceManager.GetString("STR_SA_BTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인증서버에 로그인 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_SA_HELP_LOGINALREADY_MSG {
            get {
                return ResourceManager.GetString("STR_SA_HELP_LOGINALREADY_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인증서버에 로그인하지 않았습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_SA_HELP_LOGINYET_MSG {
            get {
                return ResourceManager.GetString("STR_SA_HELP_LOGINYET_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Security Account과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_SA_MSG {
            get {
                return ResourceManager.GetString("STR_SA_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Status (활성)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_SERVERSTATUS_MSG {
            get {
                return ResourceManager.GetString("STR_SERVERSTATUS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   4afbfe8d6beedaf99d89a7f801cf9bccc342c1101436c0d0b5fda3d7846b7912과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_SHA2_CERT_SIGNUMHASH {
            get {
                return ResourceManager.GetString("STR_SHA2_CERT_SIGNUMHASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   6a385ffb4223ee95ea5ae95696639628e7dad556923f4ef79e0c904747f558ee과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_SHA2_PRK_SIGNUMHASH {
            get {
                return ResourceManager.GetString("STR_SHA2_PRK_SIGNUMHASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   인증 기능 및 상태보기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_SUBMSG_AUTHENTICATION {
            get {
                return ResourceManager.GetString("STR_SUBMSG_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   어플리케이션 사용을 위한 정보 
        ///설정, 관리 작업을 진행 합니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_SUBMSG_CONFIGUREAPPLIATION {
            get {
                return ResourceManager.GetString("STR_SUBMSG_CONFIGUREAPPLIATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   어플리케이션 사용을 위한 정보 설정, 관리 작업을 진행 합니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_SUBMSG_CONFIGUREAPPLIATIONV2 {
            get {
                return ResourceManager.GetString("STR_SUBMSG_CONFIGUREAPPLIATIONV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;사용자&apos;, &apos;장치&apos;, &apos;지문&apos; 정보의 
        ///등록 및 관리과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_SUBMSG_CONFIGUREDEVICE {
            get {
                return ResourceManager.GetString("STR_SUBMSG_CONFIGUREDEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   어플리케이션을 사용하기위한 &apos;사용자&apos;, &apos;장치&apos;, &apos;지문&apos; 정보의 등록 작업을 진행합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_SUBMSG_REGISTRATION {
            get {
                return ResourceManager.GetString("STR_SUBMSG_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;설정&apos;,&apos;변경&apos;,&apos;작업내역&apos; 등의 
        ///로그내용을 확인 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_SUBMSG_VIEWLOG {
            get {
                return ResourceManager.GetString("STR_SUBMSG_VIEWLOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DEVICE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_TAB_LOG_DEVICE {
            get {
                return ResourceManager.GetString("STR_TAB_LOG_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ETC과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_TAB_LOG_ETC {
            get {
                return ResourceManager.GetString("STR_TAB_LOG_ETC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TOTAL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_TAB_LOG_TOTAL {
            get {
                return ResourceManager.GetString("STR_TAB_LOG_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WEBSOCKET과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_TAB_LOG_WEBSOCKET {
            get {
                return ResourceManager.GetString("STR_TAB_LOG_WEBSOCKET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Authentication과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_TITLE_AUTHENTICATION {
            get {
                return ResourceManager.GetString("STR_TITLE_AUTHENTICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Configure Device과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_TITLE_DEVICE {
            get {
                return ResourceManager.GetString("STR_TITLE_DEVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제공기능 한눈에 보기.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_TITLE_MAINFORM {
            get {
                return ResourceManager.GetString("STR_TITLE_MAINFORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Registration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_TITLE_REGISTRATION {
            get {
                return ResourceManager.GetString("STR_TITLE_REGISTRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USB Connected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_USB_CONNECTED {
            get {
                return ResourceManager.GetString("STR_USB_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   USB Disconnected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_USB_DISCONNECTED {
            get {
                return ResourceManager.GetString("STR_USB_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   화상회의 로그인을 위한 웹브라우저를 실행 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string STR_VIDEOMETTING_MSG {
            get {
                return ResourceManager.GetString("STR_VIDEOMETTING_MSG", resourceCulture);
            }
        }
    }
}
